---
- name: Start HeartBeat if it is not running yet
  ## NOTE: Do NOT use Ansible "become_user"! Otherwise, ansible will fail to write .async file under /home/{{ pulsar_user }}
  # become_user: "{{ pulsar_user }}"
  shell: "cd {{ tgt_heartBeat_inst_dir }}; nohup {% if sudo_needed|bool %}sudo {% endif %} ./{{ heartBeat_bin_name.split('.gz')[0] }} -config ./runtime.yaml > /tmp/hb_start.out 2>&1 &"
  # Async shell execution with a very large number
  async: 3153600000 # 100 years
  register: hb_startSvc_cmdcat
  when: not srvStarted|trim|bool
- debug: msg="hb_startSvc_cmdcat.failed - {{ hb_startSvc_cmdcat.failed }}"
  when: show_debug_msg|bool 

- name: print command
  debug: msg="cd {{ tgt_heartBeat_inst_dir }}; nohup {% if sudo_needed|bool %}sudo {% endif %} ./{{ heartBeat_bin_name.split('.gz')[0] }} -config ./runtime.yaml"

- name: Wait until HeartBeat is ready
  wait_for:
    host: "{{ private_ip }}"
    port: "{{ hb_prometheus_port }}"
    delay: 2
    timeout: 120
  when: not srvStarted|trim|bool
